---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ipam.cfy.cz
  resources:
  - subnets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.cfy.cz
  resources:
  - subnets/finalizers
  verbs:
  - update
- apiGroups:
  - ipam.cfy.cz
  resources:
  - subnets/status
  verbs:
  - get
  - patch
  - update
