# permissions for end users to view subnets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: subnet-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ipam-for-k8s
    app.kubernetes.io/part-of: ipam-for-k8s
    app.kubernetes.io/managed-by: kustomize
  name: subnet-viewer-role
rules:
- apiGroups:
  - ipam.cfy.cz
  resources:
  - subnets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ipam.cfy.cz
  resources:
  - subnets/status
  verbs:
  - get
