apiVersion: ipam.cfy.cz/v1
kind: Subnet
metadata:
  labels:
    app.kubernetes.io/name: subnet
    app.kubernetes.io/instance: subnet-sample
    app.kubernetes.io/part-of: ipam-for-k8s
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ipam-for-k8s
  name: subnet-sample
spec:
  name: EgressIP
  address: 192.168.0.0
  mask: 255.255.255.0
  manageKind:
    apiVersion: v1
    kind: EgressIPs
  usableIPs:
    - 192.168.0.10-192.168.0.63
    - 192.168.0.128/26
  reservedIPs:
    - ipAddress: 192.168.0.1
      name: DefaultGateway
